# Generated by Django 2.0.4 on 2018-04-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180416_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment', models.CharField(blank=True, choices=[('C', 'Cash'), ('K', 'K-NET'), ('M', 'M-NET'), ('I', 'Insurance')], max_length=1, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
    ]
