# Generated by Django 2.0.4 on 2018-04-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
