# Generated by Django 2.0.4 on 2018-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180416_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='billables',
            field=models.ManyToManyField(blank=True, null=True, to='main.Billable'),
        ),
    ]
