# Generated by Django 2.0.4 on 2018-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180416_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='X', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='billables',
            field=models.ManyToManyField(to='main.Billable'),
        ),
    ]
